# Generated by Django 3.0.3 on 2020-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('actors', models.CharField(max_length=255, null=True)),
                ('cover', models.CharField(max_length=50, null=True)),
                ('directors', models.CharField(max_length=255, null=True)),
                ('score', models.FloatField(null=True)),
                ('votes', models.IntegerField(null=True)),
                ('genres', models.CharField(max_length=255, null=True)),
                ('languages', models.CharField(max_length=255, null=True)),
                ('mins', models.IntegerField(null=True)),
                ('official_site', models.CharField(max_length=255, null=True)),
                ('regions', models.CharField(max_length=255, null=True)),
                ('release_date', models.CharField(max_length=55, null=True)),
                ('slug', models.CharField(max_length=50, null=True)),
                ('storyline', models.TextField(null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField(null=True)),
                ('actor_ids', models.CharField(max_length=255, null=True)),
                ('director_ids', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_id', models.BigIntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('time', models.DateTimeField(null=True)),
                ('user_md5', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_md5', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('updatetime', models.IntegerField()),
                ('password', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=32)),
                ('user_nickname', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
